ProjektZespolowy/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("tron_app.urls"))
]

tron_app/urls.py
from django.urls import path
from . import views

app_name = "tron_app"

urlpatterns = [
    path('', views.index, name="index"),
    path("tron/", views.tron, name="tron"),
    path("tron/clean/", views.clean_board, name="clean"),
    path("tron/lastCells/", views.get_last_cells, name="lastCells"),
    path("tron/runSimulation", views.run_simulation, name="runSimulation"),
    path("tron/prepareGame", views.prepare_game, name="prepare_game")
]

tron_app/models.py
from django.db import models
from django.utils import timezone
import os


class Matrix(models.Model):
    bot_1 = models.FileField(upload_to='bots/', blank=True)
    bot_2 = models.FileField(upload_to='bots/', blank=True)
    name = models.CharField(max_length=255)
    rows = models.IntegerField(default=0)
    cols = models.IntegerField(default=0)
    result = models.CharField(max_length=500, default="Click run to start simulation")
    bot_front_view_size = models.IntegerField(default=5)
    bot_side_view_size= models.IntegerField(default=2)

    def bot_1_name(self):
        return os.path.basename(self.bot_1.name)
    def bot_2_name(self):
        return os.path.basename(self.bot_2.name)

    def __str__(self):
        return self.name


class Cell(models.Model):
    matrix = models.ForeignKey(Matrix, on_delete=models.CASCADE)
    row = models.IntegerField()
    col = models.IntegerField()
    val = models.IntegerField()
    time = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return "row:{}, column:{}".format(self.row, self.col)

tron_app/views.py
from django.shortcuts import render
from make_move import Simulation
from clean_matrix import clean as cleanMatrix
from django.core.files.storage import default_storage
from django.core.files.base import ContentFile
from django.conf import settings
from .models import Matrix, Cell
import os
from django.http import Http404, HttpResponse, HttpResponseRedirect
import json
from django.http import JsonResponse
from new_board import newMatrix
from Simulator import TRON_Simulator



def index(request):
    return render(request, "tron_app/index.html")


def tron(request):
    last_matrix = Matrix.objects.last()
    my_dict = {"matrix": last_matrix}

    return render(request, "tron_app/tron.html", context=my_dict)


def clean_board(request):
    if request.is_ajax():
        cleanMatrix()
        more_data = ["finish"]
        data = json.dumps(more_data)
        return HttpResponse(data, content_type="application/json")
    else:
        raise Http404



def get_last_cells(request):
    last = Matrix.objects.last().cell_set.all().order_by('-time')[:10]
    result = Matrix.objects.last().result
    queryset = last.values("row", "col", "val")
    return JsonResponse({"models_to_return": list(queryset),
                         'result' : result})


def run_simulation(request):
    if request.is_ajax():
        matrix = Matrix.objects.last()
        matrix.result = "Loading bots and obstacles"
        matrix.save()
        TRON_Simulator.run()
        more_data = ["finish"]
        data = json.dumps(more_data)
        return HttpResponse(data, content_type="application/json")
    else:
        raise Http404


def prepare_game(request):

    if request.method == 'POST':
        name = request.POST.get('matrix_name')
        bot1 = request.FILES.get('bot1')
        bot2 = request.FILES.get('bot2')
        if 'map_conf_file' in request.FILES.keys():
            TRON_Simulator.MAP_CREATED_FROM_FILE = True
            file = request.FILES.get('map_conf_file')
            path = default_storage.save(os.path.join('maps', 'map_tmp.txt'), ContentFile(file.read()))
            tmp_file = os.path.join(settings.MEDIA_ROOT, path)
            rows, cols = TRON_Simulator.load_map_from_file(tmp_file)
        else:
            TRON_Simulator.MAP_CREATED_FROM_FILE = False
            rows = int(request.POST.get('rows'))
            cols = int(request.POST.get('cols'))

        bot_front_view_size = int(request.POST.get('bot_front_view'))
        bot_side_view_size = int(request.POST.get('bot_side_view'))

        matrix = Matrix(name=name, bot_1=bot1, bot_2=bot2, rows=rows, cols=cols, bot_side_view_size=bot_side_view_size, bot_front_view_size=bot_front_view_size)
        matrix.save()
        newMatrix(matrix)
        return HttpResponseRedirect('/tron/')
    return render(request, 'tron_app/prepare_game.html')

templates/tron_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Projekt Zespołowy</title>
    <link rel="stylesheet" href="{% static 'libraries/bootstrap.css' %}">

    <script src="{% static 'libraries/jquery.js' %}"></script>
    <script src="{% static 'libraries/poper.js' %}"></script>
    <script src="{% static 'libraries/bootstrap_js.js' %}"></script>

    {% block css_block %}
    {% endblock css_block %}
</head>
<body>
<nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'tron_app:index' %}">#play</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample01"
            aria-controls="navbarsExample01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample01">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item ">
                <a class="nav-link" href="{% url "tron_app:tron" %}">Last game<span class="sr-only">(current)</span></a>
            </li>
        </ul>
    </div>
</nav>

{% block body_block %}
{% endblock body_block %}
</body>
</html>

{% block script %}
{% endblock script %}

templates/tron_app/index.html
{% extends "tron_app/base.html" %}
{% load static %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock css_block %}

{% block body_block %}

    <body class="bg">
        <br>

        <div class="container">
            <div class="jumbotron">
                <div class=buttons>
                    <a href="{% url "tron_app:prepare_game" %}" class="btn btn-primary btn-lg" role="button"
                       aria-pressed="true">Play!</a>
                </div>
            </div>
        </div>
    </body>
{% endblock body_block %}

templates/tron_app/prepare_game.html
{% extends "tron_app/base.html" %}
{% load static %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/prepare_game.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/loader.css.css' %}">
{% endblock css_block %}

{% block body_block %}
    <body class="bg">
    <br>
    <div class="loader"></div>
    <div class="container">
        <div class="jumbotron">
            <form id="matrixForm" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {#                {{ matrix_form.as_p }}#}
                <div class="form-group row justify-content-center">

                    <label for="matrix_name">Name :</label>
                    <div class="col-3"><input type="text" id="matrix_name" name="matrix_name" required></div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <div class="form-group">
                            <label for="map_conf_file">Map configuration file:</label>
                            <input type="file" class="form-control-file" id="map_conf_file" name="map_conf_file">
                        </div>
                    </div>

                    <div class="col-6">
                        <div class="col">
                            <div class="form-group">
                                <label for="rows">Rows:</label>
                                <input type="number" name="rows" value="30" min="10" max="100" id="rows"
                                       class="numbers">
                            </div>
                        </div>

                        <div class="col">
                            <div class="form-group">
                                <label for="cols">Columns:</label>
                                <input type="number" name="cols" value="30" min="10" max="100" id="cols"
                                       class="numbers">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">

                    <div class="form-group col-md-6">
                        <label for="bot1">Bot 1:</label>
                        <input type="file" class="form-control-file" id="bot1" name="bot1" required>
                    </div>

                    <div class="form-group col-md-6">
                        <label for="bot2">Bot 2:</label>
                        <input type="file" class="form-control-file" id="bot2" name="bot2" required>
                    </div>
                </div>

                <div class="form-group">
                    <label for="bot_front_view">Front view:</label>
                    <input type="number" class="numbers" id="bot_front_view" name="bot_front_view" value="5" min="1"
                           required>
                </div>

                <div class="form-group">
                    <label for="bot_side_view">Side view:</label>
                    <input type="number" class="numbers" id="bot_side_view" name="bot_side_view" value="2" min="1"
                           required>
                </div>


                <div class="form-group row justify-content-center">
                    <button type="submit" class="btn btn-primary mb-2">Generate new game</button>
                </div>

            </form>
        </div>
    </div>
    </body>

{% endblock body_block %}

{% block script %}
    <script>
        $("#matrixForm").submit(function (event) {
            $(".container").hide()
            $(".loader").css('visibility', 'visible')
        });
    </script>
{% endblock %}

templates/tron_app/tron.html
{% extends "tron_app/base.html" %}
{% load my_tags %}
{% load static %}

{% block css_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/tron.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/loader.css' %}">
{% endblock css_block %}

{% block body_block %}
    <body class="bg">
        <div class="loader"></div>
        <div class="container" align="center">
            <h3 id="titleHeader">{{ matrix.result }}</h3>
            <div class="jumbotron">
                <table class="myTable" align="center">
                    <div class="divTable">
                        {% for cell in matrix.cell_set.all %}
                            {% if forloop.counter|modulo:matrix.cols == 1 %}
                                <tr>
                            {% endif %}
                            {% if cell.val == 0 %}
                                <td class="white"></td>
                            {% endif %}
                            {% if cell.val == 1 %}
                                <td class="blue"></td>
                            {% endif %}
                            {% if cell.val == 2 %}
                                <td class="red"></td>
                            {% endif %}
                            {% if cell.val == 9 %}
                                <td class="black"></td>
                            {% endif %}
                        {% endfor %}
                    </div>
                </table>
            </div>
            <div class="buttons">
                <button type="button" class="runBots btn btn-primary btn-lg">Run Bots</button>
                <button type="button" class="cleanBtn btn btn-primary btn-lg">Reset</button>
            </div>
        </div>
    </body>
{% endblock body_block %}

{% block script %}
    <script>
        var mytime = 100;
        var buttons = $("button")
        var result = $("#titleHeader").text()

        function changeButtonsDisabledState(setBoolean) {
            buttons.attr('disabled', setBoolean)
        }

        function getLastCells() {
            $.ajax({
                type: "GET",
                url: "{% url "tron_app:lastCells" %}",
                success: function (data) {
                    my_data = data.models_to_return;
                    grab_result = data.result
                    if (grab_result != result) {
                        result = grab_result
                        $("#titleHeader").text(result)
                    }
                    for (i = 0; i < my_data.length; i++) {
                        var cell = my_data[i];
                        if (cell.val == 1) {
                            $("tr").eq(cell.row).find("td").eq(cell.col).css("background", "blue");
                        } else if (cell.val == 2) {
                            $("tr").eq(cell.row).find("td").eq(cell.col).css("background", "red");
                        } else if (cell.val == 9) {
                            $("tr").eq(cell.row).find("td").eq(cell.col).css("background", "black");
                        }
                    }
                }
            })
        }



        function clean() {
            $(".container").hide()
            $(".loader").css('visibility', 'visible')
            {#clearInterval(myInterval)#}
            $.ajax(
                {
                    url: '{% url "tron_app:clean" %}',
                    success: function (data) {
                        $(".jumbotron").load({% url "tron_app:tron" %} +" .myTable");
                        $("#titleHeader").text("Click run to start simulation");
                        result = "Click run to start simulation"
                        {#myInterval = setInterval(getLastCells, mytime);#}
                        $(".loader").css('visibility', 'hidden')
                        $(".container").show()
                    }
                }
            )
        }

        function run() {
            if(result != "Click run to start simulation"){
                clean()
            }
            var myInterval = setInterval(getLastCells, mytime);
            changeButtonsDisabledState(true)
            $.ajax(
                {
                    url: '{% url "tron_app:runSimulation" %}',
                    success: function (data) {
                        changeButtonsDisabledState(false)
                        clearInterval(myInterval);
                    }
                }
            )
        }

        $(".cleanBtn").click(clean)

        $(".runBots").click(run)

    </script>
{% endblock script %}